name: Run Python Script and Commit

on: [push]

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # or any version you prefer

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'Toby Manders'
        git config --global user.email 'trm2124@gmail.com'
        git add -A
        git diff --staged --quiet || git commit -m "Update images"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

